package marketplacefulfillment

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/azure"
    "net/http"
    "context"
    "github.com/Azure/go-autorest/tracing"
)

// Client is the REST API for MarketplaceFulfillment.
type Client struct {
    BaseClient
}
// NewClient creates an instance of the Client client.
func NewClient(xMsMarketplaceToken string, xMsRequestid string, xMsCorrelationid string) Client {
    return NewClientWithBaseURI(DefaultBaseURI, xMsMarketplaceToken, xMsRequestid, xMsCorrelationid)
}

// NewClientWithBaseURI creates an instance of the Client client.
    func NewClientWithBaseURI(baseURI string, xMsMarketplaceToken string, xMsRequestid string, xMsCorrelationid string) Client {
        return Client{ NewWithBaseURI(baseURI, xMsMarketplaceToken, xMsRequestid, xMsCorrelationid)}
    }

// Resolve resolve marketplace subscription.
func (client Client) Resolve(ctx context.Context) (result Subscription, err error) {
    if tracing.IsEnabled() {
        ctx = tracing.StartSpan(ctx, fqdn + "/Client.Resolve")
        defer func() {
            sc := -1
            if result.Response.Response != nil {
                sc = result.Response.Response.StatusCode
            }
            tracing.EndSpan(ctx, sc, err)
        }()
    }
        req, err := client.ResolvePreparer(ctx)
    if err != nil {
    err = autorest.NewErrorWithError(err, "marketplacefulfillment.Client", "Resolve", nil , "Failure preparing request")
    return
    }

            resp, err := client.ResolveSender(req)
            if err != nil {
            result.Response = autorest.Response{Response: resp}
            err = autorest.NewErrorWithError(err, "marketplacefulfillment.Client", "Resolve", resp, "Failure sending request")
            return
            }

            result, err = client.ResolveResponder(resp)
            if err != nil {
            err = autorest.NewErrorWithError(err, "marketplacefulfillment.Client", "Resolve", resp, "Failure responding to request")
            }

    return
    }

    // ResolvePreparer prepares the Resolve request.
    func (client Client) ResolvePreparer(ctx context.Context) (*http.Request, error) {
                    const APIVersion = "2018-08-31"
        queryParameters := map[string]interface{} {
        "api-version": APIVersion,
        }

        preparer := autorest.CreatePreparer(
    autorest.AsPost(),
    autorest.WithBaseURL(client.BaseURI),
    autorest.WithPath("/resolve"),
    autorest.WithQueryParameters(queryParameters),
    autorest.WithHeader("x-ms-marketplace-token", client.XMsMarketplaceToken))
            if len(client.XMsRequestid) > 0 {
            preparer = autorest.DecoratePreparer(preparer,
            autorest.WithHeader("x-ms-requestid",autorest.String(client.XMsRequestid)))
            }
            if len(client.XMsCorrelationid) > 0 {
            preparer = autorest.DecoratePreparer(preparer,
            autorest.WithHeader("x-ms-correlationid",autorest.String(client.XMsCorrelationid)))
            }
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ResolveSender sends the Resolve request. The method will close the
    // http.Response Body if it receives an error.
    func (client Client) ResolveSender(req *http.Request) (*http.Response, error) {
        sd := autorest.GetSendDecorators(req.Context(), autorest.DoRetryForStatusCodes(client.RetryAttempts, client.RetryDuration, autorest.StatusCodesForRetry...))
            return autorest.SendWithSender(client, req, sd...)
            }

// ResolveResponder handles the response to the Resolve request. The method always
// closes the http.Response Body.
func (client Client) ResolveResponder(resp *http.Response) (result Subscription, err error) {
    err = autorest.Respond(
    resp,
    client.ByInspecting(),
    azure.WithErrorUnlessStatusCode(http.StatusOK),
    autorest.ByUnmarshallingJSON(&result),
    autorest.ByClosing())
    result.Response = autorest.Response{Response: resp}
        return
    }

